# Generated by Django 5.0.7 on 2024-08-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=256)),
                ('lister_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lister', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_comment', models.TextField(max_length=256)),
                ('commenter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter_name', to=settings.AUTH_USER_MODEL)),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_comment', to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_name', to=settings.AUTH_USER_MODEL)),
                ('listing_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.listing')),
            ],
        ),
    ]
