# Generated by Django 5.0.7 on 2024-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
